### ISSUE TITLE
Undefined index: file

### ISSUE THREAD

**Issue by babakmoeinifar** [imanghafoori1/laravel-self-test#1]
When I use php artisan check:route, I got this error:

`
ErrorException  : Undefined index: file

  at /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/Commands/CheckRoute.php:95
    91|                 $this->checkView($ctrl, $method, $_['children']);
    92|             }
    93| 
    94|             if (! $_['children']) {
  > 95|                 dump($_['file'].'.blade.php line number:'.$_['lineNumber'].  '  =>  '.trim($_['line']). '  file does not exist:  '.$_['name'].'.blade.php');
    96|             }
    97|         }
    98|     }
    99| }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
      /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/Commands/CheckRoute.php:95

  2   Imanghafoori\LaravelSelfTest\Commands\CheckRoute::checkView()
      /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/Commands/CheckRoute.php:84
`

**Comment by imanghafoori1** [comment]
I think it should be fixed by now.

**Comment by imanghafoori1** [comment]
![image](https://user-images.githubusercontent.com/6961695/77560076-929e5f80-6eda-11ea-8482-9ccb9cafb1ed.png)

**Comment by imanghafoori1** [comment]
![microscope](https://user-images.githubusercontent.com/6961695/78522127-920e9e80-77e1-11ea-869a-05a29466e6b0.png)
