### ISSUE TITLE
Error in some functions

### ISSUE THREAD

**Issue by babakmoeinifar** [imanghafoori1/laravel-self-test#9]
In these functions:

`php artisan check:view
php artisan check:psr4
php artisan check:import
php artisan check:all`

I got this error:

`   ErrorException  : Uninitialized string offset: 1

  at /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/GetClassProperties.php:67
    63|             ])) {
    64|                 $type = $tokens[$i][0];
    65|                 for ($j = $i + 1; $j < count($tokens); $j++) {
    66|                     if ($tokens[$j] === '{') {
  > 67|                         $class = $tokens[$i + 2][1];
    68|                     }
    69|                 }
    70|             }
    71|         }

  Exception trace:

  1   Illuminate\Foundation\Bootstrap\HandleExceptions::handleError()
      /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/GetClassProperties.php:67

  2   Imanghafoori\LaravelSelfTest\GetClassProperties::getImports()
      /var/www/html/PTC/vendor/imanghafoori/laravel-self-test/src/GetClassProperties.php:28
`

**Comment by imanghafoori1** [comment]
please mention the exact version number of self-test you have installed. 
And please send me a sample file in your project which re-creates the same error.
